<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('createdAt' => 'DESC'));
    }

    public function findHighestRatedImages()
    {
        $images = $this->createQueryBuilder('i')
            ->select('i as image')
            ->addSelect('count(ratings) as stars')
            ->innerJoin('i.ratings', 'ratings')
            ->groupBy('i.id')
            ->orderBy('stars', 'DESC')
            ->getQuery()
            ->setMaxResults(3)
            ->getResult()
        ;

        return $images;
    }

    public function findImagesByTags($tag)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:Image', 'i')
            ->innerJoin('i.tags','t')
            ->where('t.name = :tag')
            ->setParameter('tag', $tag)
            ->getQuery()
            ->getResult();
    }
}
