parameters:

services:
    app.image_voter:
        class: AppBundle\Security\ImageVoter
        tags:
            - { name: security.voter }
        public: false

    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    app.cacheimage_listener:
        class: AppBundle\EventListener\CacheImageListener
        arguments: ["@liip_imagine.cache.manager"]
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: fos_user_profile }

    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager", "@validator"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
            - { name: kernel.event_listener, event: oneup_uploader.validation, method: onValidate }